import 'package:drift/drift.dart';
import 'package:hisabet/core/database/tables/contacts.dart';

class Transactions extends Table {
  TextColumn get id => text()(); // UUID
  TextColumn get contactId => text().references(Contacts, #id)();

  // Enum stored as int index or string. Int is faster.
  IntColumn get type => integer()();
  IntColumn get status => integer().withDefault(const Constant(0))();

  // Store amount as Text for Decimal precision
  TextColumn get amount => text()();

  DateTimeColumn get date => dateTime()();
  TextColumn get description => text().nullable()();

  IntColumn get cartons => integer().nullable()();
  IntColumn get qtyPerCarton => integer().nullable()();
  TextColumn get unitPrice => text().nullable()();

  // JSON string for metadata
  TextColumn get metadata => text().nullable()();

  // Shared Reference ID (e.g. Bill #, Ticket #) for smart matching
  TextColumn get referenceId => text().nullable()();

  // If this transaction was auto-generated by a POS sale, link back to it
  TextColumn get saleId => text().nullable()();

  // Tracks if the transaction has been pushed to the cloud
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();

  // Soft-delete tracking
  BoolColumn get isDeleted => boolean().withDefault(const Constant(false))();
  DateTimeColumn get deletedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
